### PR TITLE
Add export for CROSS_COMPILE environment variable

### PR DESCRIPTION
**Pull request by DavidGarriou**
I propose to systematically export CROSS_COMPILE value environment variable so that the value of the variable is taken into account for each sub-processes launched during build process (typically during make)

### CODE REVIEW

**Comment by avpatel** [comment]
Hi David,

Its great that you updated the docs but in Xvisor we follow Linux kernel style development. Its customary for everyone to send patch to xvisor-devel@googlegroups.com using "git send-email" command. It would be great if you can send your patch to xvisor-devel. Also make sure your patch has "Signed-off-by: Your Name <your_email@example.com>".

Thanks,
Anup

**Comment by avpatel** [comment]
Hi David,

Can you share your email ID?

I can send the patch to xvisor-devel on-behalf of you and also merge the same.

Regards,
Anup

**Comment by DavidGarriou** [comment]
Hi Anup,

I was not aware that you wanted me to send it by mail.
Let me send the patch this afternoon.

Regards,
David


David Garriou
+33 613 504 246

**Comment by avpatel** [comment]
This patch has been merged now.

**Pull request closed without merging**
